version: 1  # Версия конфигурационного формата. На данный момент поддерживается только версия 1.
disable_existing_loggers: False  # Не отключаем существующие логгеры, чтобы не нарушить работу других компонентов

formatters: # Определяем форматы для сообщений логирования
  detailed: # Название форматтера
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # Формат сообщения

filters: # Определяем фильтры для сообщений логирования
  level_filter: # Название фильтра
    (): '9_2_sample_DICT_CONFIG.LevelFilter'  # Класс фильтра в формате 'module.ClassName'
    min_level: 30  # Параметр для фильтра: минимальный уровень сообщений

handlers: # Определяем обработчики для логирования
  console: # Название обработчика
    class: 'logging.StreamHandler'  # Класс обработчика для вывода сообщений в консоль
    formatter: 'detailed'  # Применяем форматтер 'detailed'
    filters: [ 'level_filter' ]  # Применяем фильтр 'level_filter'

loggers: # Определяем конфигурацию логгеров
  root: # Корневой логгер
    handlers: [ 'console' ]  # Используем обработчик 'console'
    level: 'DEBUG'  # Уровень логирования для корневого логгера